/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomButton {
    }
    interface CustomTitle {
    }
}
declare global {
    interface HTMLCustomButtonElement extends Components.CustomButton, HTMLStencilElement {
    }
    var HTMLCustomButtonElement: {
        prototype: HTMLCustomButtonElement;
        new (): HTMLCustomButtonElement;
    };
    interface HTMLCustomTitleElement extends Components.CustomTitle, HTMLStencilElement {
    }
    var HTMLCustomTitleElement: {
        prototype: HTMLCustomTitleElement;
        new (): HTMLCustomTitleElement;
    };
    interface HTMLElementTagNameMap {
        "custom-button": HTMLCustomButtonElement;
        "custom-title": HTMLCustomTitleElement;
    }
}
declare namespace LocalJSX {
    interface CustomButton {
    }
    interface CustomTitle {
    }
    interface IntrinsicElements {
        "custom-button": CustomButton;
        "custom-title": CustomTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-button": LocalJSX.CustomButton & JSXBase.HTMLAttributes<HTMLCustomButtonElement>;
            "custom-title": LocalJSX.CustomTitle & JSXBase.HTMLAttributes<HTMLCustomTitleElement>;
        }
    }
}
